project:
  type: website

website:
  title: Matt Dray
  description: Matt Dray's personal website
  favicon: resources/pfp-pixel.ico
  site-url: https://www.matt-dray.com
  twitter-card: true
  search: false
  navbar:
    logo: resources/pfp-pixel.ico
    left:
      - text: Bio
        href: index.qmd
      - href: projects.qmd
      - href: talking.qmd
      - text: "Blog>"
        href: https://www.rostrum.blog
      - text: "GitHub>"
        href: https://github.com/matt-dray/
    right:
      - text: "{{< fa bugs >}}"
        href: site-details.qmd

format:
  html:
    theme: simplex
    css: styles.css
    grid:
      body-width: 900px

filters:
  - auto-dark